### ISSUE TITLE
You can eat yourself without touching a part of the snake

### ISSUE THREAD

**Issue by dante-carvajal** [jocelo/snake-game#1]
There is a bug in the game as you can eat yourself without touching a part of the snake, see image attached for reference;

![photo_2019-03-12_15-36-53](https://user-images.githubusercontent.com/16866157/54300793-385a8700-4583-11e9-90ab-e0fc370d4eb1.jpg)

**Comment by dante-carvajal** [comment]
intalalo rai nau

**Comment by jocelo** [comment]
listoooo! nomas me tarde poquito n_n
